apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app
  namespace: argocd4
  labels:
    app: demo-app
spec:
  replicas: 8
  selector:
    matchLabels:
      app: demo-app
  template:
    metadata:
      labels:
        app: demo-app
    spec:
      containers:
      - name: nginx
        image: nginx:1.21
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: /usr/share/nginx/html
          name: demo-volume
      volumes:
      - name: demo-volume
        persistentVolumeClaim:
          claimName: demo-pvc
